name: iOS Build
on: [push]
jobs:
  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          # Install base dependencies
          npm install

          # Install expo CLI and core packages
          npm install expo@latest
          npm install -g expo-cli

          # Install expo-router and related packages
          npx expo install expo-router react-native-safe-area-context react-native-screens expo-linking expo-constants expo-status-bar
          
      - name: Setup EAS
        run: |
          # Create necessary configuration files
          echo '{
            "cli": {
              "version": ">= 3.13.3"
            },
            "build": {
              "development": {
                "developmentClient": true,
                "distribution": "internal"
              },
              "preview": {
                "distribution": "internal",
                "ios": {
                  "simulator": true
                }
              },
              "production": {}
            }
          }' > eas.json

          # Update app.json with required fields
          echo '{
            "expo": {
              "name": "iFree",
              "slug": "iFree",
              "version": "1.0.0",
              "orientation": "portrait",
              "icon": "./assets/icon.png",
              "userInterfaceStyle": "light",
              "scheme": "ifree",
              "splash": {
                "image": "./assets/splash.png",
                "resizeMode": "contain",
                "backgroundColor": "#ffffff"
              },
              "assetBundlePatterns": [
                "**/*"
              ],
              "ios": {
                "supportsTablet": true,
                "bundleIdentifier": "com.freestyle.app"
              },
              "android": {
                "adaptiveIcon": {
                  "foregroundImage": "./assets/adaptive-icon.png",
                  "backgroundColor": "#ffffff"
                },
                "package": "com.freestyle.app"
              },
              "web": {
                "bundler": "metro",
                "favicon": "./assets/favicon.png"
              },
              "plugins": [
                "expo-router"
              ]
            }
          }' > app.json

          # Install EAS CLI
          npm install -g eas-cli
          
      # Set CI environment variable and use it for Expo build
      - name: Build iOS App
        env:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}
          CI: 1
        run: |
          # Build with preview profile
          npx eas build --platform ios --profile preview --non-interactive --no-wait
        
      - name: Get Build URL
        run: echo "Check the logs above for your build URL. Once the build completes, you can download the IPA from the Expo dashboard." 